name: script_core

up:
  - xcode_clt
  - ruby:
      version: 2.5.0
  - bundler
  - submodules

commands:
  recompile:
    syntax: ""
    desc: "Compiles native extension"
    run: bin/rake clobber compile
  compile:
    syntax: ""
    desc: "Compiles native extension"
    run: bin/rake compile
  spec:
    syntax: ""
    desc: "Run specs"
    run: bin/rake spec
